version: '3.8'

services:
  disc-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf # Optional: if you have a custom nginx config